services: 
    db:
        image: mysql:5.7
        restart: always
        networks: 
            slims-net:
                ipv4_address: 172.50.1.3
        container_name: slims-db
        env_file: 
            - db_default.env
        command: --sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION --max_allowed_packet=1024M
        # volumes:
        #    - slims_database_volume:/var/lib/mysql
        ports:
           - "3306:3306"
    web:
        build: 
            context: .
            dockerfile: Dockerfile
        restart: always
        networks: 
            slims-net:
                ipv4_address: 172.50.1.11
        container_name: slims-app
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - "./app:/var/www/html"

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        networks: 
            slims-net:
                ipv4_address: 172.50.1.12
        environment:
            MYSQL_USERNAME: root
            MYSQL_ROOT_PASSWORD: root
        restart: always
        ports:
            - 8181:80

volumes:
  slims_database_volume:
    driver: local
    driver_opts:
      type: none
      device: "/mnt/e/Projects/docker/slims/data"
      o: bind
        
networks: 
    slims-net:
        name: slims-net
        ipam:
            driver: default
            config:
              - subnet: "172.50.1.0/24"
